# Runs CI tasks on pull requests and pushes

name: Continuous Integration

on:
    push:
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        # skips linting if commit message contains "skip lint"
        if: "!contains(github.event.head_commit.message, 'skip lint')"

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                node-version: 12.x

            - name: Restore npm cache
              uses: actions/cache@v2
              id: cache
              with:
                path: ./node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-node-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm i

            - name: Run Linter
              run: npm run lint
